name: finance_tracker
description: Application for tracking income and expenses

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^4.2.8
  cubes: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter: ^1.27.0

flutter:
  uses-material-design: true